### ISSUE TITLE
bug: Incorrect package name causes dependency installation exception

### ISSUE THREAD

**Issue by shuaijinchao** [heiyeluren/XMM#9]
Using `xmm` in the package name will cause abnormal installation of dependencies, it should be updated to `github.com/heiyeluren/xmm`

the error is as follows:
```bash
$ go mod vendor
go: finding module for package github.com/heiyeluren/xmm/src
go: found github.com/heiyeluren/xmm/src in github.com/heiyeluren/xmm v0.1.1
go: xmm/example imports
        github.com/heiyeluren/xmm/src: github.com/heiyeluren/xmm@v0.1.1: parsing go.mod:
        module declares its path as: xmm
                but was required as: github.com/heiyeluren/xmm
```

**Comment by heiyeluren** [comment]
感谢意见~
目前已经修改了 go.mod 还有去掉了src目录~
后面操作建议是：
`
import(
    xmm "github.com/heiyeluren/xmm"
)
`
最后xmm要小写哦~

然后可以：
`
go get github.com/heiyeluren/xmm
`

就可以在你程序里顺利使用 XMM 啦~ 感谢

**Comment by Zhang-Jun-tao** [comment]
最近版本已经解决了
